/**
 * Auto-generated event types - DO NOT EDIT
 * Generated by: cargo run --bin codegen
 * Source: rust/src/bin/codegen.rs
 */

/** All GPUI event types */
export type GPUIEventType =
    | "click"
    | "dblclick"
    | "mousedown"
    | "mouseup"
    | "mousemove"
    | "mouseenter"
    | "mouseleave"
    | "hover"
    | "keydown"
    | "keyup"
    | "keypress"
    | "focus"
    | "blur"
    | "scroll"
    | "wheel"
    | "focusin"
    | "focusout";

/** React-style event handler prop names */
export type GPUIEventPropName =
    | "onClick"
    | "onDoubleClick"
    | "onMouseDown"
    | "onMouseUp"
    | "onMouseMove"
    | "onMouseEnter"
    | "onMouseLeave"
    | "onHover"
    | "onKeyDown"
    | "onKeyUp"
    | "onKeyPress"
    | "onFocus"
    | "onBlur"
    | "onScroll"
    | "onWheel";

/** Maps React prop names to event types */
export const EVENT_PROP_TO_TYPE = {
    onClick: "click",
    onDoubleClick: "dblclick",
    onMouseDown: "mousedown",
    onMouseUp: "mouseup",
    onMouseMove: "mousemove",
    onMouseEnter: "mouseenter",
    onMouseLeave: "mouseleave",
    onHover: "hover",
    onKeyDown: "keydown",
    onKeyUp: "keyup",
    onKeyPress: "keypress",
    onFocus: "focus",
    onBlur: "blur",
    onScroll: "scroll",
    onWheel: "wheel",
} as const;

/** Maps event types to React prop names */
export const EVENT_TYPE_TO_PROP = {
    click: "onClick",
    dblclick: "onDoubleClick",
    mousedown: "onMouseDown",
    mouseup: "onMouseUp",
    mousemove: "onMouseMove",
    mouseenter: "onMouseEnter",
    mouseleave: "onMouseLeave",
    hover: "onHover",
    keydown: "onKeyDown",
    keyup: "onKeyUp",
    keypress: "onKeyPress",
    focus: "onFocus",
    blur: "onBlur",
    scroll: "onScroll",
    wheel: "onWheel",
} as const;

/** Check if a prop name is an event handler */
export function isEventHandlerProp(prop: string): prop is GPUIEventPropName {
    return prop in EVENT_PROP_TO_TYPE;
}

/** Mouse event types */
export const MOUSE_EVENT_TYPES = [
    "click",
    "dblclick",
    "mousedown",
    "mouseup",
    "mousemove",
    "mouseenter",
    "mouseleave",
    "hover",
] as const;

/** Keyboard event types */
export const KEYBOARD_EVENT_TYPES = [
    "keydown",
    "keyup",
    "keypress",
] as const;

/** Focus event types */
export const FOCUS_EVENT_TYPES = [
    "focus",
    "blur",
    "focusin",
    "focusout",
] as const;

/** Scroll event types */
export const SCROLL_EVENT_TYPES = [
    "scroll",
    "wheel",
] as const;
