/**
 * Auto-generated event types - DO NOT EDIT
 * Generated by: cargo run --bin codegen
 * Source: rust/src/bin/codegen.rs
 */

/** All GPUI event types */
export type GPUIEventType =
    | "click"
    | "dblclick"
    | "mousedown"
    | "mouseup"
    | "mousemove"
    | "mouseenter"
    | "mouseleave"
    | "hover"
    | "keydown"
    | "keyup"
    | "keypress"
    | "focus"
    | "blur"
    | "scroll"
    | "wheel"
    | "input"
    | "change"
    | "beforeinput"
    | "focusin"
    | "focusout";

/** React-style event handler prop names */
export type GPUIEventPropName =
    | "onClick"
    | "onDoubleClick"
    | "onMouseDown"
    | "onMouseUp"
    | "onMouseMove"
    | "onMouseEnter"
    | "onMouseLeave"
    | "onHover"
    | "onKeyDown"
    | "onKeyUp"
    | "onKeyPress"
    | "onFocus"
    | "onBlur"
    | "onScroll"
    | "onWheel"
    | "onInput"
    | "onChange"
    | "onBeforeInput";

/** Maps React prop names to event types */
export const EVENT_PROP_TO_TYPE = {
    onClick: "click",
    onDoubleClick: "dblclick",
    onMouseDown: "mousedown",
    onMouseUp: "mouseup",
    onMouseMove: "mousemove",
    onMouseEnter: "mouseenter",
    onMouseLeave: "mouseleave",
    onHover: "hover",
    onKeyDown: "keydown",
    onKeyUp: "keyup",
    onKeyPress: "keypress",
    onFocus: "focus",
    onBlur: "blur",
    onScroll: "scroll",
    onWheel: "wheel",
    onInput: "input",
    onChange: "change",
    onBeforeInput: "beforeinput",
} as const;

/** Maps event types to React prop names */
export const EVENT_TYPE_TO_PROP = {
    click: "onClick",
    dblclick: "onDoubleClick",
    mousedown: "onMouseDown",
    mouseup: "onMouseUp",
    mousemove: "onMouseMove",
    mouseenter: "onMouseEnter",
    mouseleave: "onMouseLeave",
    hover: "onHover",
    keydown: "onKeyDown",
    keyup: "onKeyUp",
    keypress: "onKeyPress",
    focus: "onFocus",
    blur: "onBlur",
    scroll: "onScroll",
    wheel: "onWheel",
    input: "onInput",
    change: "onChange",
    beforeinput: "onBeforeInput",
} as const;

/** Check if a prop name is an event handler */
export function isEventHandlerProp(prop: string): prop is GPUIEventPropName {
    return prop in EVENT_PROP_TO_TYPE;
}

/** Mouse event types */
export const MOUSE_EVENT_TYPES = [
    "click",
    "dblclick",
    "mousedown",
    "mouseup",
    "mousemove",
    "mouseenter",
    "mouseleave",
    "hover",
] as const;

/** Keyboard event types */
export const KEYBOARD_EVENT_TYPES = ["keydown", "keyup", "keypress"] as const;

/** Focus event types */
export const FOCUS_EVENT_TYPES = ["focus", "blur", "focusin", "focusout"] as const;

/** Scroll event types */
export const SCROLL_EVENT_TYPES = ["scroll", "wheel"] as const;

/** Input event types */
export const INPUT_EVENT_TYPES = ["input", "change", "beforeinput"] as const;

// ============ Event Data Interfaces ============

/** Base event data from Rust */
export interface RawEventDataBase {
    windowId: number;
    elementId: number;
    eventType: GPUIEventType;
    timestamp: number;
}

/** Raw mouse event data from Rust */
export interface RawMouseEventData extends RawEventDataBase {
    clientX: number;
    clientY: number;
    offsetX: number;
    offsetY: number;
    button: number;
}

/** Raw keyboard event data from Rust */
export interface RawKeyboardEventData extends RawEventDataBase {
    key: string;
    code: string;
    repeat: boolean;
    ctrlKey: boolean;
    shiftKey: boolean;
    altKey: boolean;
    metaKey: boolean;
}

/** Raw scroll event data from Rust */
export interface RawScrollEventData extends RawEventDataBase {
    deltaX: number;
    deltaY: number;
    deltaMode: number;
}

/** Raw focus event data from Rust */
export interface RawFocusEventData extends RawEventDataBase {
    relatedTarget: number | null | undefined;
}

/** Raw input event data from Rust */
export interface RawInputEventData extends RawEventDataBase {
    value: string;
    data: string | null | undefined;
    inputType: string;
    isComposing: boolean;
}

/** All raw event data types */
export type RawEventData =
    | RawMouseEventData
    | RawKeyboardEventData
    | RawScrollEventData
    | RawFocusEventData
    | RawInputEventData
    | RawEventDataBase;

/** Type guard: Check if event is a mouse event */
export function isMouseEventData(data: RawEventData): data is RawMouseEventData {
    return MOUSE_EVENT_TYPES.includes(data.eventType as any);
}

/** Type guard: Check if event is a keyboard event */
export function isKeyboardEventData(data: RawEventData): data is RawKeyboardEventData {
    return KEYBOARD_EVENT_TYPES.includes(data.eventType as any);
}

/** Type guard: Check if event is a scroll event */
export function isScrollEventData(data: RawEventData): data is RawScrollEventData {
    return SCROLL_EVENT_TYPES.includes(data.eventType as any);
}

/** Type guard: Check if event is a focus event */
export function isFocusEventData(data: RawEventData): data is RawFocusEventData {
    return FOCUS_EVENT_TYPES.includes(data.eventType as any);
}

/** Type guard: Check if event is an input event */
export function isInputEventData(data: RawEventData): data is RawInputEventData {
    return INPUT_EVENT_TYPES.includes(data.eventType as any);
}
